version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/insall_nginx.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root