version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies if any  # Removed parentheses
      # OR, if you want to keep the parentheses, use quotes:
      # - echo "Installing dependencies (if any)"
  pre_build:
    commands:
      - echo Pre-build phase (e.g., linting, testing)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the HTML website
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: .